-- Run this once in your Supabase project's SQL editor
-- (Project → SQL Editor → New query → paste → Run)
--
-- NOTE: if you already ran an earlier version of this file, the old
-- "tournaments" table (name/sport/status/start_date/prize_pool only) needs
-- to be dropped first — this DELETES any rows already in it. Uncomment the
-- line below only if you're okay losing that data (there should be none
-- yet, since nothing in the app has written to it so far).
-- drop table if exists tournaments;
-- checking
create table if not exists tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sport text not null,
  city text not null,
  venue text not null,
  format text,
  tag text,
  image_url text,
  description text,
  entry_fee_amount numeric not null,
  entry_fee_unit text not null default 'team',
  prize_pool numeric not null default 0,
  prize_pool_is_trophy boolean not null default false,
  advance_amount numeric,
  first_prize numeric,
  second_prize numeric,
  start_date date not null,
  end_date date,
  date_note text,
  start_time text,
  rules text,
  other_contact text,
  trophy_details text,
  hot boolean not null default false,
  status text not null default 'pending'
    check (status in ('pending', 'live', 'rejected', 'completed', 'cancelled')),
  rejection_reason text,
  organizer_name text not null,
  organizer_email text not null,
  organizer_phone text not null,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

-- Safe to re-run: adds the columns above to a "tournaments" table that
-- already exists from an earlier version of this file, without touching
-- existing rows.
alter table tournaments add column if not exists image_url text;
alter table tournaments add column if not exists description text;
alter table tournaments add column if not exists advance_amount numeric;
alter table tournaments add column if not exists first_prize numeric;
alter table tournaments add column if not exists second_prize numeric;
alter table tournaments add column if not exists start_time text;
alter table tournaments add column if not exists rules text;
alter table tournaments add column if not exists other_contact text;
alter table tournaments add column if not exists trophy_details text;
alter table tournaments add column if not exists pincode text;
alter table tournaments add column if not exists address text;
alter table tournaments add column if not exists instagram_id text;

-- Lets admins pick which live tournament (if any) shows in the homepage
-- announcement bar (see LiveTicker.jsx); slots_left is optional and only
-- surfaces there when set.
alter table tournaments add column if not exists announce boolean not null default false;
alter table tournaments add column if not exists slots_left integer;

-- Short stable number used to build public URLs like
-- /explore/hell-in-a-cell-matrixx-turf-42 — the trailing number is what's
-- actually looked up (see getTournamentBySeq in lib/tournaments.js); the
-- name/organizer text before it is cosmetic for SEO/readability only.
alter table tournaments add column if not exists seq bigint generated by default as identity;
create unique index if not exists tournaments_seq_key on tournaments (seq);

-- organizer_email was dropped from the app (neither form collects it
-- anymore), but tables created from an earlier version of this file still
-- have it as not-null. Guarded so it's a no-op on fresh installs where the
-- column was never created in the first place.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'tournaments' and column_name = 'organizer_email'
  ) then
    alter table tournaments alter column organizer_email drop not null;
  end if;
end $$;

alter table tournaments enable row level security;

-- Storage bucket for organizer-uploaded posters. Public so the site can
-- render the image via its public URL with no signed-URL dance; uploads
-- only ever happen server-side (service_role, via /api/upload/poster),
-- so no public storage.objects policies are needed.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'tournament-posters',
  'tournament-posters',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Public site (anon key) can only read tournaments marked "live".
-- Nothing else is exposed to anon — inserts happen through the
-- /api/tournaments/submit route using the service_role key, which forces
-- status = 'pending' server-side regardless of what the client sends.
-- The admin panel also uses the service_role key, which bypasses RLS entirely.
-- Dropped-then-recreated so this whole file stays safe to run more than once.
drop policy if exists "Public can read live tournaments" on tournaments;
create policy "Public can read live tournaments"
  on tournaments for select
  using (status = 'live');

-- Promotion add-ons organizers can buy when submitting a tournament (Instagram
-- post/story/reel, HOT badge, announcement bar, poster/reel design, etc).
-- Admin-managed via /admin/pricing; the public form fetches active rows
-- through /api/promotion-packages so prices never live in frontend JS.
create table if not exists promotion_packages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  price numeric not null default 0,
  price_unit text,
  allow_quantity boolean not null default false,
  requires_telegram_upload boolean not null default false,
  is_free boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table promotion_packages enable row level security;

-- No public policies here on purpose, same as contact_messages below: public
-- reads happen through /api/promotion-packages (active rows only) and admin
-- writes through /api/admin/pricing/*, both using the service_role key.
-- Nothing is exposed to the anon key directly.

-- One-time seed of the initial package lineup — only fires on a fresh table,
-- so it's safe to re-run and won't clobber prices an admin has since edited.
insert into promotion_packages
  (name, description, price, price_unit, allow_quantity, requires_telegram_upload, is_free, sort_order)
select * from (values
  ('Instagram Post', 'Promote your tournament with one dedicated Instagram post.', 49::numeric, null::text, false, false, false, 10),
  ('Instagram Story', 'Get your tournament featured on our Instagram story for quick visibility.', 20::numeric, 'story', true, false, false, 20),
  ('Instagram Reel', 'We''ll publish your reel on our Instagram page to maximize reach. Note: you must send your reel via Telegram after submitting.', 79::numeric, null::text, false, true, false, 30),
  ('HOT Listing', 'Your tournament will be marked with a HOT badge and shown in the Featured/Hot section of the TournamentWala website, giving it higher visibility than regular tournaments.', 30::numeric, null::text, false, false, false, 40),
  ('Announcement Bar', 'Your tournament will appear in the announcement bar at the top of the TournamentWala website, making it one of the first things every visitor sees.', 49::numeric, null::text, false, false, false, 50),
  ('Website Listing', 'Every approved tournament is published on TournamentWala with its own dedicated page.', 0::numeric, null::text, false, false, true, 60),
  ('Poster Design', 'Don''t have a tournament poster? Our team will design a professional tournament poster for you.', 250::numeric, null::text, false, false, false, 70),
  ('Reel Creation', 'Don''t have a promotional reel? We''ll create a professional Instagram reel for your tournament using your details, photos, and logos.', 500::numeric, null::text, false, true, false, 80)
) as seed(name, description, price, price_unit, allow_quantity, requires_telegram_upload, is_free, sort_order)
where not exists (select 1 from promotion_packages);

-- Snapshot of what was selected/paid for at submission time (not a live join
-- to promotion_packages) so historical totals stay correct even if an admin
-- edits prices later. promotion_total is always computed server-side in
-- /api/tournaments/submit — never trusted from the client.
alter table tournaments add column if not exists promotions jsonb not null default '[]'::jsonb;
alter table tournaments add column if not exists promotion_total numeric not null default 0;

-- Razorpay order/payment id for paid submissions (promotion_total > 0),
-- verified server-side in /api/tournaments/submit before the row is ever
-- inserted — see lib/razorpay.js. Null for free-only submissions, which
-- never go through Razorpay Checkout at all.
alter table tournaments add column if not exists razorpay_order_id text;
alter table tournaments add column if not exists razorpay_payment_id text;

-- Marks packages where our team designs/creates the asset from scratch
-- (Poster Design, Reel Creation) rather than just publishing something the
-- organizer already has (Instagram Post/Story/Reel). Selecting one of these
-- on the public form opens the extra "poster/reel brief" section below —
-- see requires_telegram_upload above for the same admin-toggle pattern.
alter table promotion_packages add column if not exists requires_brief boolean not null default false;
update promotion_packages set requires_brief = true where name in ('Poster Design', 'Reel Creation');

-- Payment is now collected/verified through Razorpay Checkout at submission
-- time (see /api/tournaments/submit), so the old "send a payment screenshot"
-- instruction seeded above no longer applies — fix it on rows seeded before
-- this change without touching descriptions an admin has since edited.
update promotion_packages
  set description = 'We''ll publish your reel on our Instagram page to maximize reach. Note: you must send your reel via Telegram after submitting.'
  where name = 'Instagram Reel' and description like '%payment screenshot%';

-- Extra creative-brief info collected only when the organizer selects
-- Poster Design and/or Reel Creation, so our design team has what it needs.
-- Deliberately separate from the core listing fields above (name, sport,
-- venue, dates, format, entry fee, prize, poster) which are never re-asked.
-- promo_brief_mode/promo_brief_text hold the info when the organizer chooses
-- to dump it all as one paragraph instead of filling the fields below.
alter table tournaments add column if not exists banner_url text;
alter table tournaments add column if not exists whatsapp_number text;
alter table tournaments add column if not exists organizer_email text;
alter table tournaments add column if not exists organizer_website text;
alter table tournaments add column if not exists google_maps_link text;
alter table tournaments add column if not exists registration_last_date date;
alter table tournaments add column if not exists reporting_time text;
alter table tournaments add column if not exists team_size text;
alter table tournaments add column if not exists max_teams integer;
alter table tournaments add column if not exists ball_type text;
alter table tournaments add column if not exists third_prize numeric;
alter table tournaments add column if not exists prize_pool_is_trophy boolean not null default false;
alter table tournaments add column if not exists other_awards text;
alter table tournaments add column if not exists registration_link text;
alter table tournaments add column if not exists registration_qr_url text;
alter table tournaments add column if not exists registration_status text;
alter table tournaments add column if not exists tournament_type_tag text;
alter table tournaments add column if not exists gender_tag text;
alter table tournaments add column if not exists promo_brief_mode text;
alter table tournaments add column if not exists promo_brief_text text;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tournaments_registration_status_check'
  ) then
    alter table tournaments add constraint tournaments_registration_status_check
      check (registration_status is null or registration_status in ('open', 'closing_soon', 'closed'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'tournaments_gender_tag_check'
  ) then
    alter table tournaments add constraint tournaments_gender_tag_check
      check (gender_tag is null or gender_tag in ('men', 'women', 'mixed'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'tournaments_promo_brief_mode_check'
  ) then
    alter table tournaments add constraint tournaments_promo_brief_mode_check
      check (promo_brief_mode is null or promo_brief_mode in ('structured', 'freeform'));
  end if;
end $$;

-- Organizer accounts (Supabase Auth: Google + email/password). One row per
-- auth.users id, kept in sync automatically by the trigger below so both
-- signup methods populate it the same way with no app code involved.
create table if not exists profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table profiles enable row level security;

drop policy if exists "Users can view own profile" on profiles;
create policy "Users can view own profile"
  on profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile"
  on profiles for update
  using (auth.uid() = id);

-- Auto-creates a profiles row whenever someone signs up, whether via Google
-- (name/avatar come from raw_user_meta_data) or email+password (name comes
-- from the "full_name" passed in signUp options.data). security definer so
-- it can insert despite RLS above.
create or replace function public.handle_new_profile()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_profile();

-- Links a tournament back to the signed-in organizer who submitted it via
-- /api/tournaments/submit. Nullable because tournaments created directly in
-- the admin panel (/admin/tournaments/new) have no organizer account.
alter table tournaments add column if not exists organizer_user_id uuid references auth.users (id);

-- Additive to "Public can read live tournaments" below (permissive policies
-- are OR'd) — lets a signed-in organizer see all their own submissions
-- (pending/rejected/live) on their /profile page, not just live ones.
drop policy if exists "Organizers can read own tournaments" on tournaments;
create policy "Organizers can read own tournaments"
  on tournaments for select
  using (auth.uid() = organizer_user_id);

create table if not exists contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  phone text,
  reason text not null default 'general'
    check (reason in ('general', 'player', 'organizer')),
  message text not null,
  status text not null default 'new'
    check (status in ('new', 'read', 'replied')),
  created_at timestamptz not null default now()
);

alter table contact_messages enable row level security;

-- No public policies here on purpose: inserts happen through the
-- /api/contact/submit route using the service_role key. Nothing is
-- exposed to the anon key — only the admin panel (also service_role)
-- reads these.

-- Coordinates geocoded from a tournament's pincode (see lib/geocode.js),
-- cached here so /explore-tournaments can sort by distance from the
-- visitor without geocoding on every page view. Null until geocoding
-- succeeds for that row.
alter table tournaments add column if not exists latitude double precision;

-- Single-row settings for a site-wide promotion discount, managed from
-- /admin/pricing. When active, `percentage` is knocked off every paid
-- promotion package's price (see lib/promotionPackages.js#applyDiscount)
-- and `message` is shown as a highlighted banner on the package picker
-- (components/PromotionPackages.jsx). Singleton enforced via fixed id.
create table if not exists promotion_discount (
  id integer primary key default 1,
  message text,
  percentage numeric not null default 0
    check (percentage >= 0 and percentage <= 100),
  is_active boolean not null default false,
  updated_at timestamptz not null default now(),
  constraint promotion_discount_singleton check (id = 1)
);

alter table promotion_discount enable row level security;

-- No public policies here on purpose, same pattern as promotion_packages:
-- reads happen through /api/promotion-packages and writes through
-- /api/admin/discount, both using the service_role key.

insert into promotion_discount (id, message, percentage, is_active)
values (1, null, 0, false)
on conflict (id) do nothing;
alter table tournaments add column if not exists longitude double precision;

-- Actual number of teams that took part, filled in via the admin edit form
-- (or by the organizer on the public post-tournament form). Usually unknown
-- until after the event, so it's optional and typically set later by
-- editing the tournament. Summed across live/completed tournaments for the
-- homepage "Teams" stat (see getHomepageStats in lib/tournaments.js).
alter table tournaments add column if not exists total_teams integer;

-- Manually-logged business costs (rent, salaries, ads, etc.), managed from
-- /admin/expenses. The admin Expenses/Analytics summary cards also show a
-- Razorpay charges figure, computed live as 2.5% of period income (see
-- lib/expenses.js#computeRazorpayCharge) so that figure can never drift out
-- of sync with actual order totals. Separately, /api/tournaments/submit
-- auto-inserts one row per paid order here with category = 'Razorpay' (see
-- lib/expenses.js#RAZORPAY_CATEGORY) purely as a visible per-order ledger
-- entry — every sum over this table excludes that category so it isn't
-- double-counted against the live figure above.
create table if not exists expenses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null default 'Other',
  amount numeric not null,
  expense_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table expenses enable row level security;

-- No public policies here on purpose, same pattern as promotion_packages/
-- contact_messages: only the admin panel (service_role via supabaseAdmin())
-- ever reads/writes this table.

-- Blog posts, written and published from /admin/blogs. content is stored as
-- a JSON array of paragraph strings (matches how the admin form edits it —
-- one textarea per paragraph) rather than a single blob, so the public blog
-- pages can render clean <p> tags without needing a markdown parser.
create table if not exists blogs (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null,
  keywords text,
  meta_description text,
  cover_image_url text,
  content jsonb not null default '[]'::jsonb,
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists blogs_slug_key on blogs (slug);

alter table blogs enable row level security;

-- Public site (anon key) can only read published posts. Admin panel uses
-- the service_role key (supabaseAdmin()), which bypasses RLS entirely, so
-- drafts stay invisible to everyone else.
drop policy if exists "Public can read published blogs" on blogs;
create policy "Public can read published blogs"
  on blogs for select
  using (status = 'published');

-- One row per player who slides-to-register on a tournament page and
-- confirms their name/phone (see SwipeToRegister.jsx + /api/registrations/submit).
-- tournament_name/sport/city/pincode are snapshotted at registration time
-- (not a live join to tournaments) so the admin /admin/players table still
-- shows correct context even if the tournament is later edited or deleted.
create table if not exists registrations (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid references tournaments (id) on delete set null,
  tournament_name text not null,
  sport text not null,
  city text not null,
  pincode text,
  player_name text not null,
  player_phone text not null,
  wants_updates boolean not null default true,
  created_at timestamptz not null default now()
);

-- Safe to re-run if "registrations" already existed before wants_updates
-- was added.
alter table registrations add column if not exists wants_updates boolean not null default true;

-- Links a registration back to the signed-in player who submitted it via
-- /api/registrations/submit (see SwipeToRegister.jsx). Nullable because
-- older rows predate sign-in being required.
alter table registrations add column if not exists user_id uuid references auth.users (id);

alter table registrations enable row level security;

-- No public insert policy here on purpose, same pattern as contact_messages:
-- inserts happen through /api/registrations/submit using the service_role
-- key. Only the admin panel (also service_role) reads all rows.

-- Additive: lets a signed-in player read their own past registrations on
-- their /profile page (permissive policies are OR'd, so this doesn't open
-- up reading other players' rows).
drop policy if exists "Players can read own registrations" on registrations;
create policy "Players can read own registrations"
  on registrations for select
  using (auth.uid() = user_id);

-- Additive: lets an organizer read the registrations for tournaments they
-- posted, via the /profile "view registered players" panel. The app code
-- actually does this read through the service_role client with an explicit
-- ownership check (see app/api/organizer/tournaments/[id]/registrations),
-- so this policy is defense-in-depth, not load-bearing.
drop policy if exists "Organizers can read registrations for own tournaments" on registrations;
create policy "Organizers can read registrations for own tournaments"
  on registrations for select
  using (
    exists (
      select 1 from tournaments
      where tournaments.id = registrations.tournament_id
        and tournaments.organizer_user_id = auth.uid()
    )
  );

-- Backs lib/rateLimit.js — a small fixed-window rate limiter for public POST
-- routes (admin login, tournament/registration/contact submit, poster
-- upload). Vercel functions are stateless/serverless, so an in-memory
-- counter wouldn't be reliable across invocations; this table + the
-- function below give every route a shared, atomic counter instead.
create table if not exists rate_limits (
  key text primary key,
  window_start timestamptz not null,
  count integer not null default 1
);

-- No RLS policies here on purpose, same pattern as contact_messages/
-- promotion_packages: only ever touched via service_role (supabaseAdmin()),
-- never exposed to the anon key.
alter table rate_limits enable row level security;

-- Atomic "check and increment" for a fixed window: starts a fresh window
-- (count = 1) if this key has never been seen or its window has expired,
-- otherwise increments and returns false once count exceeds p_limit. Done
-- as a single upsert (not a select-then-update from the app) so concurrent
-- requests for the same key can't both read the same count before either
-- writes back, which would let more requests through than the limit allows.
create or replace function rate_limit_hit(p_key text, p_limit int, p_window_seconds int)
returns boolean as $$
declare
  current_count int;
begin
  insert into rate_limits (key, window_start, count)
  values (p_key, now(), 1)
  on conflict (key) do update
    set count = case
        when rate_limits.window_start < now() - make_interval(secs => p_window_seconds)
          then 1
        else rate_limits.count + 1
      end,
      window_start = case
        when rate_limits.window_start < now() - make_interval(secs => p_window_seconds)
          then now()
        else rate_limits.window_start
      end
  returning count into current_count;

  return current_count <= p_limit;
end;
$$ language plpgsql security definer set search_path = public;
