-- Run this once in your Supabase project's SQL editor
-- (Project → SQL Editor → New query → paste → Run)
--
-- NOTE: if you already ran an earlier version of this file, the old
-- "tournaments" table (name/sport/status/start_date/prize_pool only) needs
-- to be dropped first — this DELETES any rows already in it. Uncomment the
-- line below only if you're okay losing that data (there should be none
-- yet, since nothing in the app has written to it so far).
-- drop table if exists tournaments;

create table if not exists tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sport text not null,
  city text not null,
  venue text not null,
  format text,
  tag text,
  image_url text,
  description text,
  entry_fee_amount numeric not null,
  entry_fee_unit text not null default 'team',
  prize_pool numeric not null default 0,
  advance_amount numeric,
  first_prize numeric,
  second_prize numeric,
  start_date date not null,
  end_date date,
  date_note text,
  start_time text,
  rules text,
  other_contact text,
  trophy_details text,
  hot boolean not null default false,
  status text not null default 'pending'
    check (status in ('pending', 'live', 'rejected', 'completed', 'cancelled')),
  rejection_reason text,
  organizer_name text not null,
  organizer_email text not null,
  organizer_phone text not null,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

-- Safe to re-run: adds the columns above to a "tournaments" table that
-- already exists from an earlier version of this file, without touching
-- existing rows.
alter table tournaments add column if not exists image_url text;
alter table tournaments add column if not exists description text;
alter table tournaments add column if not exists advance_amount numeric;
alter table tournaments add column if not exists first_prize numeric;
alter table tournaments add column if not exists second_prize numeric;
alter table tournaments add column if not exists start_time text;
alter table tournaments add column if not exists rules text;
alter table tournaments add column if not exists other_contact text;
alter table tournaments add column if not exists trophy_details text;
alter table tournaments add column if not exists pincode text;
alter table tournaments add column if not exists address text;
alter table tournaments add column if not exists instagram_id text;

-- Lets admins pick which live tournament (if any) shows in the homepage
-- announcement bar (see LiveTicker.jsx); slots_left is optional and only
-- surfaces there when set.
alter table tournaments add column if not exists announce boolean not null default false;
alter table tournaments add column if not exists slots_left integer;

-- Short stable number used to build public URLs like
-- /explore/hell-in-a-cell-matrixx-turf-42 — the trailing number is what's
-- actually looked up (see getTournamentBySeq in lib/tournaments.js); the
-- name/organizer text before it is cosmetic for SEO/readability only.
alter table tournaments add column if not exists seq bigint generated by default as identity;
create unique index if not exists tournaments_seq_key on tournaments (seq);

-- organizer_email was dropped from the app (neither form collects it
-- anymore), but tables created from an earlier version of this file still
-- have it as not-null. Guarded so it's a no-op on fresh installs where the
-- column was never created in the first place.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_name = 'tournaments' and column_name = 'organizer_email'
  ) then
    alter table tournaments alter column organizer_email drop not null;
  end if;
end $$;

alter table tournaments enable row level security;

-- Storage bucket for organizer-uploaded posters. Public so the site can
-- render the image via its public URL with no signed-URL dance; uploads
-- only ever happen server-side (service_role, via /api/upload/poster),
-- so no public storage.objects policies are needed.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'tournament-posters',
  'tournament-posters',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Public site (anon key) can only read tournaments marked "live".
-- Nothing else is exposed to anon — inserts happen through the
-- /api/tournaments/submit route using the service_role key, which forces
-- status = 'pending' server-side regardless of what the client sends.
-- The admin panel also uses the service_role key, which bypasses RLS entirely.
-- Dropped-then-recreated so this whole file stays safe to run more than once.
drop policy if exists "Public can read live tournaments" on tournaments;
create policy "Public can read live tournaments"
  on tournaments for select
  using (status = 'live');

-- Promotion add-ons organizers can buy when submitting a tournament (Instagram
-- post/story/reel, HOT badge, announcement bar, poster/reel design, etc).
-- Admin-managed via /admin/pricing; the public form fetches active rows
-- through /api/promotion-packages so prices never live in frontend JS.
create table if not exists promotion_packages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  price numeric not null default 0,
  price_unit text,
  allow_quantity boolean not null default false,
  requires_telegram_upload boolean not null default false,
  is_free boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table promotion_packages enable row level security;

-- No public policies here on purpose, same as contact_messages below: public
-- reads happen through /api/promotion-packages (active rows only) and admin
-- writes through /api/admin/pricing/*, both using the service_role key.
-- Nothing is exposed to the anon key directly.

-- One-time seed of the initial package lineup — only fires on a fresh table,
-- so it's safe to re-run and won't clobber prices an admin has since edited.
insert into promotion_packages
  (name, description, price, price_unit, allow_quantity, requires_telegram_upload, is_free, sort_order)
select * from (values
  ('Instagram Post', 'Promote your tournament with one dedicated Instagram post.', 49::numeric, null::text, false, false, false, 10),
  ('Instagram Story', 'Get your tournament featured on our Instagram story for quick visibility.', 20::numeric, 'story', true, false, false, 20),
  ('Instagram Reel', 'We''ll publish your reel on our Instagram page to maximize reach. Note: you must send your reel along with the payment screenshot.', 79::numeric, null::text, false, true, false, 30),
  ('HOT Listing', 'Your tournament will be marked with a HOT badge and shown in the Featured/Hot section of the TournamentWala website, giving it higher visibility than regular tournaments.', 30::numeric, null::text, false, false, false, 40),
  ('Announcement Bar', 'Your tournament will appear in the announcement bar at the top of the TournamentWala website, making it one of the first things every visitor sees.', 49::numeric, null::text, false, false, false, 50),
  ('Website Listing', 'Every approved tournament is published on TournamentWala with its own dedicated page.', 0::numeric, null::text, false, false, true, 60),
  ('Poster Design', 'Don''t have a tournament poster? Our team will design a professional tournament poster for you.', 250::numeric, null::text, false, false, false, 70),
  ('Reel Creation', 'Don''t have a promotional reel? We''ll create a professional Instagram reel for your tournament using your details, photos, and logos.', 500::numeric, null::text, false, true, false, 80)
) as seed(name, description, price, price_unit, allow_quantity, requires_telegram_upload, is_free, sort_order)
where not exists (select 1 from promotion_packages);

-- Snapshot of what was selected/paid for at submission time (not a live join
-- to promotion_packages) so historical totals stay correct even if an admin
-- edits prices later. promotion_total is always computed server-side in
-- /api/tournaments/submit — never trusted from the client.
alter table tournaments add column if not exists promotions jsonb not null default '[]'::jsonb;
alter table tournaments add column if not exists promotion_total numeric not null default 0;

-- Marks packages where our team designs/creates the asset from scratch
-- (Poster Design, Reel Creation) rather than just publishing something the
-- organizer already has (Instagram Post/Story/Reel). Selecting one of these
-- on the public form opens the extra "poster/reel brief" section below —
-- see requires_telegram_upload above for the same admin-toggle pattern.
alter table promotion_packages add column if not exists requires_brief boolean not null default false;
update promotion_packages set requires_brief = true where name in ('Poster Design', 'Reel Creation');

-- Extra creative-brief info collected only when the organizer selects
-- Poster Design and/or Reel Creation, so our design team has what it needs.
-- Deliberately separate from the core listing fields above (name, sport,
-- venue, dates, format, entry fee, prize, poster) which are never re-asked.
-- promo_brief_mode/promo_brief_text hold the info when the organizer chooses
-- to dump it all as one paragraph instead of filling the fields below.
alter table tournaments add column if not exists banner_url text;
alter table tournaments add column if not exists whatsapp_number text;
alter table tournaments add column if not exists organizer_email text;
alter table tournaments add column if not exists organizer_website text;
alter table tournaments add column if not exists google_maps_link text;
alter table tournaments add column if not exists registration_last_date date;
alter table tournaments add column if not exists reporting_time text;
alter table tournaments add column if not exists team_size text;
alter table tournaments add column if not exists max_teams integer;
alter table tournaments add column if not exists ball_type text;
alter table tournaments add column if not exists third_prize numeric;
alter table tournaments add column if not exists other_awards text;
alter table tournaments add column if not exists registration_link text;
alter table tournaments add column if not exists registration_qr_url text;
alter table tournaments add column if not exists registration_status text;
alter table tournaments add column if not exists tournament_type_tag text;
alter table tournaments add column if not exists gender_tag text;
alter table tournaments add column if not exists promo_brief_mode text;
alter table tournaments add column if not exists promo_brief_text text;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tournaments_registration_status_check'
  ) then
    alter table tournaments add constraint tournaments_registration_status_check
      check (registration_status is null or registration_status in ('open', 'closing_soon', 'closed'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'tournaments_gender_tag_check'
  ) then
    alter table tournaments add constraint tournaments_gender_tag_check
      check (gender_tag is null or gender_tag in ('men', 'women', 'mixed'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'tournaments_promo_brief_mode_check'
  ) then
    alter table tournaments add constraint tournaments_promo_brief_mode_check
      check (promo_brief_mode is null or promo_brief_mode in ('structured', 'freeform'));
  end if;
end $$;

create table if not exists contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  phone text,
  reason text not null default 'general'
    check (reason in ('general', 'player', 'organizer')),
  message text not null,
  status text not null default 'new'
    check (status in ('new', 'read', 'replied')),
  created_at timestamptz not null default now()
);

alter table contact_messages enable row level security;

-- No public policies here on purpose: inserts happen through the
-- /api/contact/submit route using the service_role key. Nothing is
-- exposed to the anon key — only the admin panel (also service_role)
-- reads these.
